### ISSUE TITLE
canine_gistic2_issue

### ISSUE THREAD

**Issue by Tianfang-Wang** [sbamin/canine_gistic2#1]
Hi @sbamin,
Thanks for your work!
I got an issue running GISTIC2 on canine data with the recompiled version. The error message is as below:
Index exceeds matrix dimensions.
Error in normalize_by_arm_length (line 74)
......
Specified key type does not match the type expected for this container.
Would you know how shall I resolve this?

THANKS

**Comment by sbamin** [comment]
Hi,

Which version of GISTIC2 and MCR are you using? Please note that we used GISTIC v2.0.22 from ftp://ftp.broadinstitute.org/pub/GISTIC2.0/ and matlab MCR/8.0. Compiling canine-compatible GISTIC2 may not work with other gistic versions and/or matlab compilers.

**Comment by Tianfang-Wang** [comment]
Thanks for your reply @sbamin!
I am using v2.023, and after recompilation, my test data (only including chromosome 1) is working fine with human reference but not canine reference. So I suspected the problem is due to the canine reference which I used the version provided in here (not familiar with matlab and I didn't make my own reference). Would you happen to have updated version of canine reference? I also tried  GISTIC v2.0.22 with MCR/8.0. However, the recompilation always has an issue somehow.

**Comment by Tianfang-Wang** [comment]
@sbamin And I was also wondering if you have compiled and downloadable package for dog. Thanks!

**Comment by sbamin** [comment]
Can you try pre-compiled matlab binary `gp_gistic2_from_seg_upd` (in this github) and see if you can run gistic2 using MCR/8.0 and GISTIC v2.0.22. Example script is at https://github.com/sbamin/canine_gistic2/blob/master/gistic_run.sh

**Comment by Tianfang-Wang** [comment]
@sbamin Trying to run the pre-compiled one, and it seems running fine. Thanks so much for your helps! I was wondering how to cite your work.

**Comment by sbamin** [comment]
Great and glad it worked. Thanks and you may cite our preprint which we submitted a few weeks back. https://doi.org/10.1101/673822
