### ISSUE TITLE
Error about canine gistic2

### ISSUE THREAD

**Issue by guanghaoli** [sbamin/canine_gistic2#3]
Hello, @sbamin. I have changed Matlab code and recompile the same as the instruction described and got the recompile canine_gistic2 ( the gistic version and matlab version is the sam also). However, an error occurred when I run the program using my data. The error file is listed as follows:
Reference to non-existent element of a cell array.

Error in normalize_by_arm_length (line 74)

Error in make_sample_B (line 50)

Error in perform_deconstruction (line 68)

Error in perform_ziggurat_deconstruction (line 120)

Error in run_focal_gistic (line 156)

Error in run_gistic20 (line 127)

Error in run_gistic2_from_seg (line 225)

Error in gp_gistic2_from_seg (line 97)

MATLAB:nonExistentCellElement

=========================
I don't know why this error occurred. Could you please help to deal with it?
Thanks,
Guanghao

**Comment by sbamin** [comment]
Hi, can you please follow issue #1  and see if that can help fix errors you are getting?

**Comment by guanghaoli** [comment]
@sbamin I tried the pre-compiled Matlab library gp_gistic2_from_seg_upd. It ran well. Thank you very much for your reply.
