### ISSUE TITLE
gistic2 for mouse data(mm10)

### ISSUE THREAD

**Issue by wangweifeng2018** [sbamin/canine_gistic2#4]
Hi @sbamin,
Thanks for your work!
I am trying to use gistic2.0.23  for mouse data. But failed to prepared refgene file (mm10.mat).

I was wondering do you know someone have done this work already ?

THANKS

**Comment by sbamin** [comment]
Hi Wang,

Sorry for much delayed reply. I doubt if there is mm10 for v2.0.23. I have tried in vain to re-compile canfam3.1 for v2.0.23 and using matlab R2019b (I don't have older versions) and there is a little support from GISTIC2 team for non-human ref genomes.
