### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by zenglongjin** [sbamin/canine_gistic2#6]
Dear sbamin:
We are using software GISTIC, but there is an error about segment overlap. How do you filter for small duplicate fragments?
Thank you very much for your attention and consideration.
Sincerely yours,
Zenglongjin

**Comment by sbamin** [comment]
HI Zenglongjin,

I am not a core developer for GISTIC2. I suggest to contact developers at [GISTIC2 homepage](https://www.genepattern.org/modules/docs/GISTIC_2.0) or [GISTIC2 forum](https://groups.google.com/a/broadinstitute.org/g/gistic-forum)
